---
- dest: ./src/components/
  friendlyName: FunctionComponent(FC)
  nameCase: pascal
  structure:
    - type: file
      name: index
      extension: ts
      content:
        src: ./_tpl/index.ts
    - type: file
      suffix: .styles
      extension: ts
      content:
        src: ./_tpl/FC/Component.styles.ts
    - type: file
      suffix: .types
      extension: ts
      content:
        src: ./_tpl/FC/Component.types.ts
    - type: file
      extension: tsx
      content:
        src: ./_tpl/FC/Component.base.tsx
    - type: folder
      name: tests
      content:
        - type: file
          suffix: .test
          extension: tsx
          content:
            src: ./_tpl/Component.tst.tsx
    - type: folder
      name: stories
      content:
        - type: file
          suffix: .stories
          extension: tsx
          content:
            src: ./_tpl/Component.stories.tsx

- dest: ./src/components/
  friendlyName: Simple Component | ForwardRefComponent w/o State & Context
  nameCase: pascal
  structure:
    - type: file
      prefix: render
      extension: tsx
      content:
        src: ./_tpl/SimpleComponent/Component.base.tsx
    - type: file
      name: index
      extension: ts
      content:
        src: ./_tpl/index.ts
    - type: file
      extension: tsx
      content:
        src: ./_tpl/SimpleComponent/Component.tsx
    - type: file
      suffix: .types
      extension: ts
      content:
        src: ./_tpl/SimpleComponent/Component.types.ts
    - type: file
      prefix: use
      extension: ts
      content:
        src: ./_tpl/useComponent.ts
    - type: file
      prefix: use
      suffix: Styles
      extension: ts
      content:
        src: ./_tpl/SimpleComponent/Component.styles.ts
    - type: folder
      name: tests
      content:
        - type: file
          suffix: .test
          extension: tsx
          content:
            src: ./_tpl/Component.tst.tsx
    - type: folder
      name: stories
      content:
        - type: file
          suffix: .stories
          extension: tsx
          content:
            src: ./_tpl/Component.stories.tsx

- dest: ./src/components/
  friendlyName: Full Component | ForwardRefComponent w/ State & Context
  nameCase: pascal
  structure:
    - type: file
      name: index
      extension: ts
      content:
        src: ./_tpl/index.ts
    - type: file
      extension: tsx
      content:
        src: ./_tpl/FullComponent/Component.tsx
    - type: file
      prefix: use
      suffix: ContextValues
      extension: ts
      content:
        src: ./_tpl/FullComponent/useComponentContextValues.ts
    - type: file
      suffix: Context
      extension: tsx
      content:
        src: ./_tpl/FullComponent/ComponentContext.tsx
    - type: file
      suffix: .types
      extension: ts
      content:
        src: ./_tpl/FullComponent/Component.types.ts
    - type: file
      prefix: render
      extension: tsx
      content:
        src: ./_tpl/FullComponent/renderComponent.tsx
    - type: file
      prefix: use
      extension: ts
      content:
        src: ./_tpl/useComponent.ts
    - type: file
      prefix: use
      suffix: Styles
      extension: ts
      content:
        src: ./_tpl/FullComponent/useComponentStyles.ts
    - type: folder
      name: tests
      content:
        - type: file
          suffix: .test
          extension: tsx
          content:
            src: ./_tpl/Component.tst.tsx
    - type: folder
      name: stories
      content:
        - type: file
          suffix: .stories
          extension: tsx
          content:
            src: ./_tpl/Component.stories.tsx
